name: CI
on:
  push:
    branches: [ develop ]
  workflow_dispatch: # Permite rodar manualmente no GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        # Adicione este step após o 'npm install'
      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test
